services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=deepseek-r1:1.5b
      - OLLAMA_DEFAULT_MODEL=deepseek-r1:1.5b
    networks:
      ai_network:
        aliases:
          - ollama
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: serve

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ai_network
    command: pull deepseek-r1:1.5b

  gogent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogent
    depends_on:
      ollama-init:
        condition: service_completed_successfully
    environment:
      - PROVIDER=OLLAMA
      - MODEL=deepseek-r1:1.5b
      - NATS_URL=nats://localhost:4222
      - OLLAMA_HOST=http://ollama:11434
      - API_KEY=${API_KEY:-}
      - AGENT_NAME=${AGENT_NAME:-Agent Sig}
    volumes:
      - ./data:/app/data:rw
    ports:
      - "4222:4222"
    networks:
      ai_network:
        aliases:
          - gogent

networks:
  ai_network:
    name: ai_agent_network
    driver: bridge

volumes:
  ollama_data: